steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  timeout: '1600s'
serviceAccount: 'projects/core-waters-419214/serviceAccounts/cloudbuild@core-waters-419214.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
